// Type declarations for rigModels.mjs (auto-generated by scripts/gen_rig_models.mjs).
// World-space voxels: [x, y, z, color] where y is up.

export interface RigModel {
  cube: number;
  armX: number;
  legX: number;
  cxAll: number;
  cz: number;
  pivots: {
    hip: number; knee: number; torso: number; head: number;
    eye: number; hair: number;
    arm: number; hand: number; weapon: number; pad: number;
    elbow: number; wrist: number;
  };
  parts: {
    head: [number, number, number, number][];
    torso: [number, number, number, number][];
    armL: [number, number, number, number][];
    foreL: [number, number, number, number][];
    armR: [number, number, number, number][];
    foreR: [number, number, number, number][];
    legL: [number, number, number, number][];
    shinL: [number, number, number, number][];
    legR: [number, number, number, number][];
    shinR: [number, number, number, number][];
  };
}

export function gregRigModel(): RigModel;
export function patronRigModel(): RigModel;